[tool.poetry]
name = "luigi-demo"
version = "0.1.0"
description = ""
authors = ["Orbio <vikram@orbio.earth>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
luigi = "^3.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
